name: "Validate JSON files and deploy to GitHub Pages"

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  validate-and-deploy:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x

      - name: Validate schema
        run: ./validate.sh

      - name: Push to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          clean: true
